import Intro from '@/components/Intro/Intro'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '@/components/Footer/Footer'
import NewProducts from '@/components/NewProducts/NewProducts'


export default function Home() {
  return (
    <>
      <Head>
        <title>lampastore.ru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <NewProducts />
    </>
  )
}
