import Intro from '@/components/Intro/Intro'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '@/components/Footer/Footer'
import NewProducts from '@/components/NewProducts/NewProducts'
import styles from '@/styles/ProductPage.module.scss'
import { motion } from 'framer-motion'
import { Swiper, SwiperSlide } from 'swiper/react';
import { Thumbs, Navigation } from 'swiper/modules';
import 'swiper/css';


export default function Home() {
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  return (
    <>
      <Head>
        <title>lampastore.ru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.section key="subcategorycatalog" transition={{duration: 0.5, delay: 0.5, easings: "linear"}} exit={{opacity: 0}} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className={styles.body}>
        <h2 className={styles.title}>EVIAN ONE</h2>
        <div className={styles.content}>
          <div className={`${styles.swiper} productpage-swiper`}>
            {thumbsSwiper && (
              <Swiper  
                modules={[Thumbs, Navigation]}
                thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}
                navigation={true}
                spaceBetween={0} 
                slidesPerView={1}
                className={styles.slides}
              >
                <SwiperSlide><Image src="/product-1.jpg" alt="" width={845.44} height={845.44} draggable="false"/></SwiperSlide>
                <SwiperSlide><Image src="/product-2.png" alt="" width={845.44} height={845.44} draggable="false"/></SwiperSlide>
                <SwiperSlide><Image src="/product-3.png" alt="" width={845.44} height={845.44} draggable="false"/></SwiperSlide>
                <SwiperSlide><Image src="/product-4.png" alt="" width={845.44} height={845.44} draggable="false"/></SwiperSlide>
                <SwiperSlide><Image src="/product-5.png" alt="" width={845.44} height={845.44} draggable="false"/></SwiperSlide>
              </Swiper>
            )}
            <Swiper  
              modules={[Thumbs]}
              watchSlidesProgress
              onSwiper={setThumbsSwiper} 
              spaceBetween={0}
              slidesPerView="auto"
              direction="vertical"
            >
              <SwiperSlide><Image src="/product-1.jpg" alt="" width={216.36} height={216.36} draggable="false"/></SwiperSlide>
              <SwiperSlide><Image src="/product-2.png" alt="" width={216.36} height={216.36} draggable="false"/></SwiperSlide>
              <SwiperSlide><Image src="/product-3.png" alt="" width={216.36} height={216.36} draggable="false"/></SwiperSlide>
              <SwiperSlide><Image src="/product-4.png" alt="" width={216.36} height={216.36} draggable="false"/></SwiperSlide>
              <SwiperSlide><Image src="/product-5.png" alt="" width={216.36} height={216.36} draggable="false"/></SwiperSlide>
            </Swiper>
          </div>
          <div className={styles.info}>
            <p className={styles.subtitle}>Настенный светильник с коническим текстильным абажуром на сборной стойке из латуни и хрусталя</p>
            <p className={styles.price}>14 600₽</p>
          </div>
        </div>
      </motion.section>
    </>
  )
}
